### ISSUE TITLE
Decouple consensus interface

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#1]
Add eudico's consensus interface to Lotus and implement EC behind that interface. This abstraction is the stepping-stone for Mir's integration.

**Comment by adlrocha** [comment]
Apparently the consensus interface was already introduced in Lotus in June 14th: https://github.com/filecoin-project/lotus/blob/master/chain/consensus/iface.go

We will then focus on abstracting common functions (as done in Eudico) and extend it (if needed) to make it more suitable for the Mir integration.

**Comment by jsoares** [comment]
@adlrocha will this be closed by https://github.com/filecoin-project/lotus/pull/9405? Can I move it to review/qa accordingly?

**Comment by adlrocha** [comment]
Implemented and soon to be merged to lotus `master`.
