### ISSUE TITLE
IPC: Get the checkpoint period from parent

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#165]
## Background
We currently are setting the checkpoint period in subnets when we create the genesis for a network to a default value because we didn't have a way to pick it up from the parent. This is wrong, we should set both checkpointing periods to the value configured in the subnet actor from the parent: https://github.com/consensus-shipyard/lotus/blob/b0d84dda153e52b044cafd0899817b70cc66c582/chain/gen/genesis/genesis.go#L229

## Proposal
To solve this we can include in `./eudico genesis new` the ability to optionally pass the `--ipc-agent-url` as we do in the validator. If this is done, the IPC agent will fetch the checkpoint period for the subnet for which we are generating the genesis from the parent. If `--ipc-agent-url` is not passed, we use the default value, and if it is set and the call fails, the genesis generation should also fail.

**Comment by adlrocha** [comment]
For top-down messages if https://github.com/consensus-shipyard/ipc-actors/issues/104 ends up being implemented we won't need to pick up that info anymore.

**Comment by dnkolegov** [comment]
Started implementing. The branch is here - https://github.com/consensus-shipyard/lotus/pull/170

**Comment by jsoares** [comment]
Is this still the case?

**Comment by adlrocha** [comment]
As we are deprecating Lotus, the idea was not to bother implementing this one. I think we can close this one and revive it if needed.
