### ISSUE TITLE
Set up a faucet to enable user testing 

### ISSUE THREAD

**Issue by jsoares** [consensus-shipyard/lotus#17]
In order to enable users to play around with the network, we need to set up some form of faucet that disburses some amount of testnet token. This is not a technical requirement for network launch but it's a requirement for the network to serve a wider testing purpose.

**Comment by adlrocha** [comment]
Hosted here: https://consensus-shipyard.github.io/spacenet-faucet/
Code here: https://github.com/consensus-shipyard/spacenet-faucet
