### ISSUE TITLE
Configure IPC infra scripts to use UDP by default

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#171]
In order to connect the Mir daemon and validators we currently default to choosing the `tcp` connections for this. In the most recent versions of libp2p, TCP is exclusively used as a fallback protocol for when UDP traffic is blocked for some reason in network/host. It is way more efficient in terms of connection establishment and operation to use `quic` and `tcp`. We should modify the infra scripts to connect via quic by default instead of tcp.

**Comment by dnkolegov** [comment]
Are you suggesting using QUIC instead of TCP, or using QUIC be default and TCP as a fallback?

**Comment by dnkolegov** [comment]
I should also note that Mir membership does not support fallback addresses.

**Comment by adlrocha** [comment]
> Are you suggesting using QUIC instead of TCP, or using QUIC be default and TCP as a fallback?

I was suggesting using quic as a default. I know there are no fallback addresses for Mir. This is something we should address in the future, but is not blocking. Would you mind tracking this fallback addresses issue in Mir? Thanks :pray:

**Comment by dnkolegov** [comment]
Reported - https://github.com/filecoin-project/mir/issues/457
