### ISSUE TITLE
ERROR: couldn't initialize libp2p config

### ISSUE THREAD

**Issue by shanithkk** [consensus-shipyard/lotus#182]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus Ethereum RPC
- [ ] lotus FVM - Lotus FVM interactions
- [ ] FEVM tooling
- [X] Other

### Lotus Version

```text
eudico version 1.21.0-rc2+2k+git.311a7d7dd
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

while initializing the validator ```./eudico mir validator config init``` throwing error like
```ERROR: couldn't initialize libp2p config: error creating libp2p key: open ~/.lotus/mir.key: no such file or directory```

### Tooling

```text
No
```

### Configuration Options

```text
./eudico mir validator config init
```

**Comment by dnkolegov** [comment]
Fixed in https://github.com/consensus-shipyard/lotus/pull/189
