### ISSUE TITLE
`scripts/ipc/mine-subnet.sh` has an empty line before shebang

### ISSUE THREAD

**Issue by mturilin** [consensus-shipyard/lotus#206]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus Ethereum RPC
- [ ] lotus FVM - Lotus FVM interactions
- [ ] FEVM tooling
- [X] Other

### Lotus Version

```text
All versions I assume
```

### Repro Steps

I'm using Lotus as a part of IPC following this guide https://github.com/consensus-shipyard/ipc-agent/edit/main/docs/quickstart-calibration.md

If `mine-subnet.sh` is called from a non-bash environment, it fails because there's an empty line in front of shebang.

### Describe the Bug

If `mine-subnet.sh` is called from a non-bash environment, it fails because there's an empty line in front of shebang.

### Tooling

```text
I was calling it from NGS script.
```

### Configuration Options

```text
IPC
```

**Comment by jsoares** [comment]
Fixed in https://github.com/consensus-shipyard/lotus/pull/205, will go into next release. Thanks!
