### ISSUE TITLE
Bug: Checkpoint and Block Header verification

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#26]
One of the checks we perform to verify that a block is valid is to see if the checkpoint received in a block is consistent with the latest checkpoint received, and that this checkpoint verifies all of the previous blocks received. To perform this check, we preemptively accept all blocks and cache them marking them as unverified so they can be verified by the next checkpoint. 

When a block with a checkpoint arrives, we first see if the checkpoint points to the latest checkpoint we received, and then we ensure that all the unverified blocks in the cache are verified that the blockchain (marking as bad those that are not verified, and triggering a fast-forward if needed). 

Keeping a pointer to the latest checkpoint as we do now doesn't work, because a validator may trigger at any moment a `RestoreState` and update the latest checkpoint leading to some races. As a consequence of this we are seeing some bugs sometimes where validators say that a `checkpoint doesn't point to the previous one`, or that a `checkpoint doesn't verify all blocks in cache`. We need to improve the validation algorithm so we don't have to rely on the latest checkpoint, and we are not vulnerable to these races.

**Comment by dnkolegov** [comment]
<img width="862" alt="Screenshot 2022-11-25 at 09 49 58" src="https://user-images.githubusercontent.com/6521369/203945080-e6284a68-cdb4-468d-a67c-1b1907b4f07b.png">

**Comment by adlrocha** [comment]
Some pointers to the code involved: 
* This is the check that fails because the previous checkpoint is not set correctly when restarting state: https://github.com/consensus-shipyard/lotus/blob/68d414cda1e241c377d8c2b19d275bc2d2321382/chain/consensus/mir/consensus.go#L287-L291
* Sometimes we also have an error due to the way we verify blocks in the cache, because after the crash we still have blocks in the cache from the previous run: https://github.com/consensus-shipyard/lotus/blob/68d414cda1e241c377d8c2b19d275bc2d2321382/chain/consensus/mir/cache.go#L127-L162
* Here is were we set the latest checkpoint: https://github.com/consensus-shipyard/lotus/blob/68d414cda1e241c377d8c2b19d275bc2d2321382/chain/consensus/mir/state_manager.go#L423-L431
* And here where we receive the blocks that we cache and where we do the block validation for blocks in the cache: https://github.com/consensus-shipyard/lotus/blob/68d414cda1e241c377d8c2b19d275bc2d2321382/chain/consensus/mir/consensus.go#L189-L206
