### ISSUE TITLE
Discussion: Implications of choosing a large checkpoint period for Mir

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#27]
The current validation process with Mir for full-nodes not actively participating from the consensus protocol as validators is as follows:
- A set of sanity-checks are performed over blocks that do not include a Mir checkpoint, and they are preemptively added to a cache of unverified blocks. 
- Once a block with a checkpoint arrives, this checkpoint verifies a set of previously unverified blocks. If the checkpoint signature is correct, the full-node checks what blocks verified by this checkpoints and look for them in the unverified cache, marking them as verified. If after this process, there are still blocks in the cache unverified for a height below the checkpoint received, these blocks are marked as bad and removed from the cache (ideally, we should check if we have included it in our chain, and roll-back to a previous state to sync with the right block).

This means that, essentially, checkpoints are key for the verification of individual blocks in Mir. Increasing the checkpoint period too much would result in long gaps with unverified blocks increasing the window for potential attacks. The current default checkpoint period is of 8 blocks, and due to the way Mir works, the minimum checkpoint period currently supported is of at most the number of validators in the network. 

In the future we should consider fine-tuning this value and figuring out better ways to verify blocks in isolation

//cc @dnkolegov

**Comment by sergefdrv** [comment]
I think a node could accept a block once received a sufficient number of matching block headers originating from different validators (either signed or received from authenticated p2p channels).
