### ISSUE TITLE
IPC M2 issues

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#30]
This issue tracks all the work that needs to be done towards IPC M2.
## Blockchain Instance
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] #34

## IPC Client 
- [ ] #35
- [ ] #36
- [ ] #37 
  - _(note to self, I feel this interface is included in #36. Remove and update issues and figure accordingly)._
- [ ] #38
- [ ] #39
- [ ] #42
- [ ] #43
- [ ] #41
- [ ] #40

## Actors
- [ ] https://github.com/consensus-shipyard/ipc-gateway/issues/18
- [ ] (bonus) https://github.com/consensus-shipyard/ipc-gateway/issues/8

![image](https://user-images.githubusercontent.com/6717133/206700087-bafa10cc-bbd1-4db3-b945-f59c348dfffe.png)

**Comment by jsoares** [comment]
I'm merging this into https://github.com/protocol/ConsensusLab/issues/185 to fit with the roadmap. Let's update there if needed.
