### ISSUE TITLE
Bump up Mir version and fix the computation of CID

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#74]
Once [this PR](https://github.com/filecoin-project/mir/pull/350) is merged and a new release is cut for Mir where checkpoints start being deterministic is bumped up in Eudico, we can remove the special way of computing Cid for blocks running Mir consensus:

https://github.com/consensus-shipyard/lotus/blob/262595b43a1868b383977aa378e3bdbe093f42ab/chain/types/blockheader.go#L75-L94

This will automatically fix https://github.com/consensus-shipyard/lotus/issues/25

**Comment by dnkolegov** [comment]
Fixed in https://github.com/consensus-shipyard/lotus/pull/86
