### ISSUE TITLE
Full-node support and per-block verification

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/lotus#9]
## Goal
Support for full-nodes when running Mir as a consensus algorithm,

## Description
With the Mir-based BFT consensus, the nodes can only receive a trusted block from the ordering layer. Basically the ordering layer outputs 2 things: _new blocks_ (not signed by anyone); _checkpoints_ - representations of state snapshots that do contain a quorum of signatures.

For BuilderNet, SPs are running full-nodes but they may not be running a Mir validator. For the seamless operation of SPs, is not enough for them to receive checkpoints with a summary of previous blocks, they need per-block updates, and the ability to verify the validity of this block when received through the network.

As suggested off-band by @matejpavlovic, and @sergefdrv, we can add an additional communication round to Mir in order to include validator signatures of individual blocks. Alternatively, we may also use some kind "hash-magic" to enable per-block verification.

An alternative approach proposed by @vukolic is to use learner nodes to implement full-nodes. We can probably leverage GossipSub for this. Acceptors can broadcast their accepts, and full-nodes (i.e. learners) wait for a majority of acceptors before delivering the block.

Related issues: #8, https://github.com/hyperledger/fabric-rfcs/pull/48

**Comment by matejpavlovic** [comment]
This issue, as I understand it, largely overlaps with #4

**Comment by adlrocha** [comment]
Closing in favor of #4
