### ISSUE TITLE
Mir chain misalignment after lotus sync

### ISSUE THREAD

**Issue by matejpavlovic** [consensus-shipyard/lotus#98]
It can happen that, after syncing state through Lotus, blocks are downloaded that Mir has not yet delivered.
This can easily happen when Mir falls behind and needs to catch up through `RestoreState`.
When Mir delivers the next block, that block might already have been received through Lotus.
However, the height of this block is (wrongly) computed based on the last block received from Lotus, instead of the next block height expected from Mir.

https://github.com/consensus-shipyard/lotus/blob/519b51346cadd4ab4725c0d29973fe71cf896302/chain/consensus/mir/state_manager.go#L288

**Suggested fix**: Either compute the block height correctly based on `sm.height`, or simply ignore delivered blocks that are already present (while still incrementing `sm.height`) in the implementation of `ApplyTXs`.

To make fixing easier, [Mir v0.3.0](https://github.com/filecoin-project/mir/releases/tag/v0.3.0) (which simplifies dealing with state restoration) should be used by the fixed version.

**Comment by adlrocha** [comment]
@matejpavlovic, @dnkolegov, has this been fixed already?

**Comment by matejpavlovic** [comment]
Yes it has, by #99. It just has not been linked by some accident, sorry.

**Comment by adlrocha** [comment]
No worries :) I was just doing some housekeeping. Thanks
